name: Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: semantic-pull-request
      uses: amannn/action-semantic-pull-request@v3.4.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          refactor
          feature
          release
          bugfix
          hotfix
        scopes: |
          core
          ui
        requireScope: false
        subjectPattern: (^(?![A-Z]).+$)([\w\W]{20,80})
        subjectPatternError: |
            Please ensure that the subject "{subject}" doesn't start with an uppercase character, and that it has more than 20 characters.

