name: Cache, Build & Test

on:
  push:
    branches: 
      - main
      - actions

jobs:
  test:

    name: Cache, Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
            path: Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-pods-
      - name: Install Pods
        run: |
          pod install
      - name: Build and Test
        run: |
          xcodebuild test -scheme POC-CI-Pods -workspace POC-CI-Pods.xcworkspace -destination platform="iOS Simulator",name="iPhone 11",OS=14.4
      
      - name: Generate Code Coverage Report
        uses: sersoft-gmbh/swift-coverage-action@v2
