name: Cache, Build & Test

on:
  push:
    branches: 
      - main

jobs:
  test:

    name: Cache, Build & Test
    #env:
      #SCHEME: "POC-CI-Pods"
      #DEVICE: "iPhone 12"
      #DERIVED_DATA_PATH: "DerivedData"

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 11']

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
            path: Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-pods-

      - name: Install Pods
        run: |
          pod install

      - name: Force xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
        
      - name: iPhone 11 Test
        run: xcodebuild clean test -project "POC-CI-Pods.xcodeproj" -scheme "POC-CI-Pods" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
     
      - name: Build App
        run: xcodebuild -project "POC-CI-Pods.xcodeproj" -scheme "POC-CI-Pods" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
