name: Cache, Build & Test

on:
  push:
    branches: 
      - main
      - Tools

jobs:
  test:

    name: Cache, Build & Test
    env:
      SCHEME: "POC-CI-Pods"
      DEVICE: "iPhone 12"
      DERIVED_DATA_PATH: "DerivedData"

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
            path: Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-pods-

      - name: Install Pods
        run: |
          pod install

      - name: Build and Test
        run: |
          xcodebuild test -scheme POC-CI-Pods -workspace POC-CI-Pods.xcworkspace -destination platform="iOS Simulator",name="iPhone 11",OS=14.4
    codecov:
      container:
        image: swift:5.3
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-test-discovery --enable-code-coverage
      - uses: mattpolzin/swift-codecov-action@0.6.0
        with:
        MINIMUM_COVERAGE: 0

