name: Cache, Build & Test

on:
  push:
    branches: 
      - actions

jobs:
  test:

    name: Cache, Build & Test
    #env:
      #SCHEME: "POC-CI-Pods"
      #DEVICE: "iPhone 12"
      #DERIVED_DATA_PATH: "DerivedData"

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 11']

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
            path: Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-pods-

      - name: Install Pods
        run: |
          pod install
          
      - name: Force xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
        
      - name: iPhone 11 Test
        run: xcodebuild clean test -workspace POC-CI-Pods.xcworkspace -scheme POC-CI-Pods -destination "${destination}"
        env: 
          destination: ${{ matrix.destination }} 
